name: ipaua
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - jupyterlab
  - Pillow=9.4.0
  - tqdm=4.66.4
  - scikit-learn=1.5.0
  - scipy=1.13.1
  - geopandas=0.14.4
  - geemap=0.32.1
  - folium=0.16.0
  - earthengine-api=0.1.401
  - streamlit=1.24.1
  - xgboost=2.0.3
  - pip
  - pip:
      - pysqlite3
      - fiona=1.9.6
      - gdal==3.0.2
      - pyproj==3.6.1
      - rasterio==1.3.10
      - netcdf4==1.6.4
      - xarray==2024.3.0
      - georasters==0.5.29
      - dask==2024.5.1
      - pyarrow==11.0.0
      - streamlit-option-menu==0.3.13
      - streamlit-folium==0.21.0